spring :
    servlet :
        multipart :
            max-file-size :    10MB
            max-request-size : 10MB
    datasource :

        # PostgreSQL
#        url :      jdbc:postgresql://localhost:5432/connection
        #

        # MySQL
        url :      jdbc:mysql://localhost:3306/connection
        #

        username : root
        password : Stasy2004
    jpa :
        hibernate :
            ddl-auto : update
        show-sql : true

        # PostgreSQL
#       properties :
#            hibernate :
#              dialect : org.hibernate.dialect.PostgreSQLDialect
#              jdbc :
#                   lob :
#                       non_contextual_creation : true
        #

server :
    port : 8080